### ISSUE TITLE
Document the required secrets on the README

### ISSUE THREAD

**Issue by klutchell** [product-os/flowzone#18]
```
      FLOWZONE_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_PASS:
        required: true
      BALENA_API_KEY_PUSH:
        required: true
      BALENA_API_KEY_TEST:
        required: false
      COMPOSE_VARS:
        required: false
 ```
