### ISSUE TITLE
Protect npm publish when docker tests are pending

### ISSUE THREAD

**Issue by fisehara** [product-os/flowzone#195]
When docker tests are executed but the npm tests have already succeeded the npm publish is starting.

As there is no conditional needs, the npm publish has to wait for the docker test job always and needs to evaluated further.

https://stackoverflow.com/questions/65844033/conditional-needs-in-github-action
copy-pasta from stackoverflow: 
``` yaml
jobs:
  init_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "initial run"

  conditional_job:
    runs-on: ubuntu-latest
    needs: init_job
    if: ${{ your condition here }}
    steps:
      - run: echo "conditonal run"

  final_job:
    needs: conditional_job
    if: always()
    steps:
      - name: fail if conditional job failed
        if: ${{ needs.conditional_job.result == 'failure' }}
        run: exit 1
      - run: echo "final run"
```
