### ISSUE TITLE
Programatically enable auto-merge on repo/PRs

### ISSUE THREAD

**Issue by ab77** [product-os/flowzone#252]
See, https://github.com/orgs/community/discussions/24719

Default would probably be `autoMerge = true`.

After this is implemented and all repos have migrated from resinCI, we can remove bulldozer from our infrastructure.

**Comment by ab77** [comment]
> Alternatively, if flowzone takes over merging then it can push the version commit and then merge, instead of pushing the version commit to master?

@codewithcheese I don't see why not, but it might be tricky with the way versioning is done currently. cc @klutchell

**Comment by ab77** [comment]
https://github.com/product-os/flowzone/pull/343

**Comment by klutchell** [comment]
Because you depend on `protect_branch` but protect branch only runs on open pull requests, not on finalize. We will have to change the dependencies if we only want it to run on finalize events.

**Comment by ab77** [comment]
I currently have this:

```
  repo_config:
    name: Standardise repository settngs
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    timeout-minutes: ${{ fromJSON(inputs.jobs_timeout_minutes) }}
    needs:
      - event_types
    if: |
      needs.event_types.outputs.do_final == 'true' &&
      inputs.repo_config == 'true'
    steps:
      - name: Configure repository...
```
